language: ruby
arch:
  - amd64
  - ppc64le
rvm:
  - "2.7"
  - "2.6"
  - "2.5"
cache: bundler
before_install:
  - gem update --system
  - nvm install node
env: "EXECJS_RUNTIME=MiniRacer"
matrix:
  include:
    - rvm: "2.7"
      env: "EXECJS_RUNTIME=Node"
# ppc64le related code
    - rvm: "2.7"
      arch: ppc64le
      env: "EXECJS_RUNTIME=Node"
